name: Latest blog posts

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull in latest Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@subhadeep-choudhuri"
          max_post_count: 5
          template: "- [$title]($url) &nbsp; <sub><sup>$date</sup></sub>"
